[project]
name = "agentforge"
version = "2.0.0a3"
description = "LLM-based agent for general purpose tasks"
authors = [
  { name ="PAMPAS-Lab" },
  { name = "CHEN LONGRONG", email = "longrongchen@163.com" },
  { name = "XUE YIBO", email = "yiboxue@163.com" },
  { name = "LI YAO"},
]
license = {text = "MIT"}
keywords = ["agent", "cli", "llm"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "openai>=2.6.0",
    "anthropic>=0.54.0",
    "click>=8.0.0",
    "google-genai>=1.24.0",
    "jsonpath-ng>=1.7.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "rich>=13.0.0",
    "typing-extensions>=4.0.0",
    "ollama>=0.5.1",
    "socksio>=1.0.0",
    "tree-sitter-languages==1.10.2",
    "tree-sitter==0.21.3",
    "ruff>=0.12.4",
    "keyboard>=0.13.5",
    "textual>=5.0.1",
    "prompt-toolkit>=3.0.51",
    "aiohttp>=3.12.13",
    "loguru>=0.7.3",
    "mcp>=1.13.0",
    "pytest>=8.0.0",
    "pyyaml>=6.0",
    "pytest-asyncio>=1.4.0",
    "fastapi",
    "uvicorn",
    "redis>=8.1.0",
    "chromadb>=1.5.9",
    "pymilvus>=3.0.1",
    "pypdf>=6.15.0",
    "python-docx>=1.2.0",
    "flagembedding>=1.4.0",
    "minio>=7.2.20",
]

[project.optional-dependencies]
evaluation = [
    "sb-cli>=0.1.4",
    "docker>=7.0.0",
    "tqdm>=4.66.0",
    "datasets>=2.14.0",
]

[project.scripts]
agentforge = "agentforge.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["agentforge"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "B",
    "SIM",
    "C4",
    "E4", "E9", "E7", "F",
    "I"
]

